## 本地图片上传路径
local:
  path: static
mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: test
# Home Mysql
#  username: nine
#  password: 123qwe

  # cp Mysql
  username: root
  password: 123456


#  online  , dev
#  username: root
#  password: stan183183

  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
system:
  addr: 9191
  db-type: mysql
  oss-type: local
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
zap:
  level: info
  format: console
  prefix: '[newbee_mall]'
  director: log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

token:
  token-time: "72h"

qiniu:
  access-key: 81HD1oGmq8NsGxgVQWWVJ5TBAVYbpjis1pcsM09U
  sercet-key: xefgAk3TVFPTgV_jg-P4TJMoQb2BtGeHmSy5mXDc
  bucket: wd-mall
  qiniu-server: http://wildberries.win/




#macmini sql
#http://localhost/phpMyAdmin4.8.5/sql.php?server=1&db=test&table=tb_newbee_mall_admin_user&pos=0

